name: Validate docs

on:
  push:
    branches: [ main ]
    paths:
      - "**.fsh"
      - "**/sushi-config.yaml"
  workflow_dispatch:
  
jobs:
  sushi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Sushi
        run: sudo npm install -g fsh-sushi

      - name: Validate with Sushi
        run: sushi .


  ig-publisher:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Jekyll
        run: sudo gem install jekyll

      - name: Install Sushi
        run: sudo npm install -g fsh-sushi

      - name: Install IG publisher
        run: ./_updatePublisher.sh -y

      - name: Validate IG
        run: ./_genonce.sh
