name: Make IG

on:
  push:
    branches: [ main ]
    paths:
      - "**.fsh"
      - "**/sushi-config.yaml"
  workflow_dispatch:

jobs:
  ig-publisher:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Jekyll
        run: sudo gem install jekyll

      - name: Install Sushi
        run: sudo npm install -g fsh-sushi

      - name: Install IG publisher
        run: |
          chmod +x _updatePublisher.sh
          _updatePublisher.sh -y

      - name: Validate IG
        run: |
          chmod +x _genonce.sh
          _genonce.sh
