name: Serve Sushi

on:
  push:
    branches: [ main ]
    paths:
      - "**.fsh"
      - "**/sushi-config.yaml"
  workflow_dispatch:
  
jobs:
  sushi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Sushi
        run: sudo npm install -g fsh-sushi

      - name: Validate with Sushi
        run: sushi .